"""empty message

Revision ID: 0ed0f5b13356
Revises: 123bdaca569f
Create Date: 2018-03-23 18:35:49.968529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed0f5b13356'
down_revision = '123bdaca569f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('_location_id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.String(length=32), nullable=True),
    sa.Column('_address', sa.String(length=32), nullable=True),
    sa.Column('_current_user_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
