"""empty message

Revision ID: 123bdaca569f
Revises: 4fa210e319c9
Create Date: 2018-03-19 23:01:54.528717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123bdaca569f'
down_revision = '4fa210e319c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_created')
    # ### end Alembic commands ###
