"""empty message

Revision ID: 19e377378700
Revises: 526868857b1f
Create Date: 2018-03-31 16:36:24.905609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e377378700'
down_revision = '526868857b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('matchedTopics', sa.String(length=128), nullable=True))
    op.drop_column('users', 'matchedTopic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('matchedTopic', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'matchedTopics')
    # ### end Alembic commands ###
