"""empty message

Revision ID: 526868857b1f
Revises: a96d2d790f16
Create Date: 2018-03-31 16:34:54.763736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526868857b1f'
down_revision = 'a96d2d790f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('matchedTopic', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'matchedTopic')
    # ### end Alembic commands ###
