"""empty message

Revision ID: 923f2e2ef706
Revises: 0ed0f5b13356
Create Date: 2018-03-25 20:53:26.968349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923f2e2ef706'
down_revision = '0ed0f5b13356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', sa.String(length=127), nullable=True))
    op.add_column('locations', sa.Column('currentUserCount', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('gid', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('locations', sa.Column('name', sa.String(length=127), nullable=True))
    op.add_column('locations', sa.Column('phoneNumber', sa.String(length=50), nullable=True))
    op.add_column('locations', sa.Column('priceLevel', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('rating', sa.Float(), nullable=True))
    op.drop_column('locations', '_name')
    op.drop_column('locations', '_location_id')
    op.drop_column('locations', '_current_user_count')
    op.drop_column('locations', '_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('_address', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('_current_user_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('_location_id', sa.INTEGER(), nullable=False))
    op.add_column('locations', sa.Column('_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('locations', 'rating')
    op.drop_column('locations', 'priceLevel')
    op.drop_column('locations', 'phoneNumber')
    op.drop_column('locations', 'name')
    op.drop_column('locations', 'id')
    op.drop_column('locations', 'gid')
    op.drop_column('locations', 'currentUserCount')
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###
