"""empty message

Revision ID: a96d2d790f16
Revises: 3ce6811d877c
Create Date: 2018-03-30 15:58:49.953020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96d2d790f16'
down_revision = '3ce6811d877c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('matchedMessage', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'matchedMessage')
    # ### end Alembic commands ###
