"""empty message

Revision ID: e4e17194b53c
Revises: 9c5d06b1cc7c
Create Date: 2018-03-26 23:44:25.949762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e17194b53c'
down_revision = '9c5d06b1cc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'location')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
